export const projects = [
  {
    id: 1,
    project_name: "Medi-Nova Diagnostic Center",
    server: "https://github.com/sahidDev09/Medi-Nova-server-MERN",
    client: "https://github.com/sahidDev09/Medi-Nova-client-MERN",
    live: "https://medinova-dc16a.web.app",
    description:
      "MediNova is a comprehensive diagnostic center management system designed to streamline operations for both users and administrators. This web application allows users to book and manage appointments, while administrators can oversee the entire system efficiently.",
    features: [
      "Book Appointments",
      "Cancel Appointments",
      "Authentication",
      "Responsive Design",
      "Manage Appointments",
      "User Management",
      "Dynamic Banner",
      "Statistics Charts",
    ],

    technology_uses: [
      "Jsx",
      "CSS",
      "Tailwind CSS",
      "React.js",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Figma",
      "Firebase",
    ],
    image: "/assets/images/projects-thumbnil/medi_nova.jpeg",
  },
  {
    id: 2,
    project_name: "Write-Wave",
    server: "https://github.com/sahidDev09/WriteWave-Server-Node",
    client: "https://github.com/sahidDev09/WriteWave-Client-react",
    live: "https://writewave-99267.web.app",
    description:
      "WriteWave is a dynamic and interactive blog website that allows users to post, update, and manage blogs on various topics such as entertainment, sports, health, technology, traveling, and more. The platform includes features like wishlist functionality, animations, security, and authentication with Google login.",
    features: [
      "Blog Posting",
      "Blog Updating",
      "Wishlist",
      "Animations",
      "Authentication",
    ],
    technology_uses: [
      "Jsx",
      "CSS",
      "Tailwind CSS",
      "React.js",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Figma",
      "Firebase",
    ],
    image: "/assets/images/projects-thumbnil/Write_wave.png",
  },
  {
    id: 3,
    project_name: "ArtSync Website",
    server: "https://github.com/sahidDev09/ArtSync-server",
    client: "https://github.com/sahidDev09/ArtSync-Client",
    live: "https://artsync-b902d.web.app",
    description:
      "Welcome to ArtSync, your premier destination for exploring, sharing, and synchronizing with the world of arts and crafts!",
    features: [
      "Art and Craft Categories",
      "Swiper Slider",
      "Customer Reviews",
      "Contact Page",
      "User Data Management",
    ],
    technology_uses: [
      "Jsx",
      "CSS",
      "Tailwind CSS",
      "React.js",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Figma",
      "Firebase",
    ],
    image: "/assets/images/projects-thumbnil/syncArt.jpeg",
  },
];
